language: cpp
dist: trusty
sudo: false
matrix:
  include:
    # Build Job
    - name: Tests (Stable Ubuntu gcc)
      os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXFLAGS=""  # -Werror=strict-aliasing and other GCC bugs
    # Build Job
    - name: Tests Forcing C++0x (Stable Ubuntu gcc)
      os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXFLAGS=""  # -Werror=strict-aliasing and other GCC bugs
        - CPPSTD="-std=c++0x"  # Force C++0x
    # Build Job
    - name: Tests (Latest clang5)
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    # Build Job
    - name: Tests, Examples & Docs (Latest gcc7)
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libeigen3-dev  # used by examples/robotlocalization
            - graphviz  # used by docs
            - doxygen  # used by docs
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
        - make unit-test/test_all
        # eigen3 throws warnings.
        - CXXFLAGS="" CONFIG="-I/usr/include/eigen3" make examples/all
        - make docs
    # Build Job
    - name: Tests Coverage (Latest gcc7)
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
        - make unit-test/test_coverage
        # -X POST -d "{\"body\": \"\`\`\`\n$(cat coverage/coverage.txt | awk -v ORS='\\n' '1')\`\`\`\"}" \
        - if [ "${TRAVIS_PULL_REQUEST}" != "false" ] ; then
            curl -H "Authorization: token ${COVERAGE_POSTER_API_TOKEN}" -X POST -d "{\"body\": \"\`\`\`\nTEST\`\`\`\"}" "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments";
          fi

before_install:
  - eval "${MATRIX_EVAL}"
  - $CXX --version

# Used on all jobs that don't specify a script
script:
  - make unit-test/test_all
  # Min set of examples that are considered tests pretty much
  - make examples/helloworld
  - make examples/counterwithreset
