language: cpp
dist: trusty
sudo: false
matrix:
  include:
    # Default Trust/GCC
    - name: Tests (Stable Ubuntu gcc)
      os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXFLAGS=""  # -Werror=strict-aliasing and other GCC bugs
    # Latest gcc
    - name: Tests, Examples & Docs (Latest gcc7)
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libeigen3-dev  # used by examples/robotlocalization
            - graphviz  # used by docs
            - doxygen  # used by docs
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      script:
        - make unit-test/test_all
        - CXXFLAGS="" CONFIG="-I/usr/include/eigen3" make examples/all
        - make docs
    # Latest clang
    - name: Tests (Latest clang5)
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz doxygen
  - $CXX --version

script:
  - make unit-test/test_all
  - make unit-test/test_all
  - make examples/helloworld
  - make examples/counterwithreset
