language: cpp
dist: trusty
sudo: false
matrix:
  include:
    # Default Trust/GCC
    - name: Stable Ubuntu gcc
      os: linux
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"
        - CXXFLAGS=""
    # Latest gcc
    - name: Latest gcc7
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # Latest clang
    - name: Latest clang5
      os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-5.0
          packages:
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - eval "${MATRIX_EVAL}"
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz doxygen
  - $CXX --version

script:
  - make unit-test/test_all
  - make examples/helloworld
  - make examples/counterwithreset
  - make examples/trivialvendingmachine
  - make examples/fancyvendingmachine
  - make examples/beatmachine
  - make examples/resuminggraph
  - make docs

